# Generated by Django 5.0.1 on 2025-03-28 09:56

import django.db.models.deletion
import easy_thumbnails.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(blank=True, choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("main", "Main"),
                            ("popular_product_block", "Popular Product Block"),
                            ("best_selling_block", "Best Selling Block"),
                            ("new_arrival_block", "New Arrival Block"),
                            ("new_arrival_block_left_image", "New Arrival Block Left Image"),
                            ("curated_gifts", "Curated Gifts"),
                            ("main_mobile", "Main Mobile"),
                        ],
                        max_length=50,
                    ),
                ),
                ("banner_image", easy_thumbnails.fields.ThumbnailerImageField(help_text="Main :1980 × 821 ,  others : 787 × 300", upload_to="banners/")),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.category")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="creator_%(class)s_objects", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(blank=True, choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("place", models.CharField(max_length=120)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="creator_%(class)s_objects", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
    ]
