# Generated by Django 5.0.1 on 2025-04-03 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_orderitem_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="alternative_no",
        ),
    ]
