# Generated by Django 5.0.1 on 2025-03-28 09:56

import django.db.models.deletion
import easy_thumbnails.fields
import mptt.fields
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(blank=True, choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("image", easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to="brands/")),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="creator_%(class)s_objects", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "image",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True, help_text="Recommended size: 120x120 pixels.", null=True, upload_to="categories/", verbose_name="category"
                    ),
                ),
                ("order", models.PositiveIntegerField(blank=True, null=True)),
                ("discount", models.DecimalField(decimal_places=2, default=0, help_text="Enter discount percentage for all products in this category.", max_digits=5)),
                ("is_active", models.BooleanField(default=True)),
                ("is_list_home", models.BooleanField(default=True)),
                ("is_cake", models.BooleanField(default=False)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                ("parent", mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="children", to="products.category")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="CategoryList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(blank=True, choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("title", models.CharField(max_length=128)),
                ("category", models.ForeignKey(limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.CASCADE, to="products.category")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="creator_%(class)s_objects", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Category Lists",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(blank=True, choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="creator_%(class)s_objects", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(blank=True, choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("feature_name", models.CharField(max_length=128)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="creator_%(class)s_objects", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OfferSale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(blank=True, choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("title", models.CharField(max_length=128)),
                ("image", easy_thumbnails.fields.ThumbnailerImageField(upload_to="sales/")),
                ("end_date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="creator_%(class)s_objects", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Pincode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(blank=True, choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("code", models.CharField(max_length=6)),
                ("city", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pincodes", to="products.city")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="creator_%(class)s_objects", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(blank=True, choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("product_name", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("brand", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="products.brand")),
                ("category", mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="products", to="products.category")),
                ("cities", models.ManyToManyField(blank=True, null=True, related_name="products", to="products.city")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="creator_%(class)s_objects", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Products",
                "ordering": ("product_name",),
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(blank=True, choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("varient_name", models.CharField(max_length=128)),
                ("slug", models.SlugField(unique=True)),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("actual_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("product_code", models.CharField(default=products.models.generate_product_code, max_length=100)),
                ("details", models.TextField()),
                ("thumbnail_image", easy_thumbnails.fields.ThumbnailerImageField(help_text=" The recommended size is 220x220 pixels.", upload_to="products/varients/")),
                ("generic_name", models.CharField(blank=True, max_length=200, null=True)),
                ("first_available_date", models.DateField(blank=True, null=True)),
                ("is_popular", models.BooleanField(default=False)),
                ("is_trend", models.BooleanField(default=False)),
                ("is_new_arrival", models.BooleanField(default=True)),
                ("is_best_seller", models.BooleanField(default=True)),
                ("is_offer", models.BooleanField(default=False)),
                ("is_stock", models.BooleanField(default=True)),
                ("stock", models.PositiveIntegerField(default=1)),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True, max_length=500)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="creator_%(class)s_objects", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="varients", to="products.product")),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(blank=True, choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("image", models.ImageField(help_text=" The recommended size is 800x600 pixels.", upload_to="products/")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="creator_%(class)s_objects", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("product_varient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.productvariant")),
            ],
            options={
                "ordering": ("product_varient",),
            },
        ),
        migrations.CreateModel(
            name="FeatureSpec",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(blank=True, choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("specification_name", models.CharField(max_length=128)),
                ("specification_value", models.CharField(max_length=128)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="creator_%(class)s_objects", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("feature", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.feature")),
                ("product_varient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.productvariant")),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AvailableSize",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("actual_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("variant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="available_sizes", to="products.productvariant")),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(blank=True, choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("date", models.DateField()),
                ("voucher_number", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="creator_%(class)s_objects", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(blank=True, choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("rating", models.PositiveIntegerField(default=5)),
                ("fullname", models.CharField(max_length=255)),
                ("headline", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approval", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="creator_%(class)s_objects", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="products.productvariant")),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(blank=True, choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "image",
                    easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text="if Image Availible add", null=True, upload_to="subcategories/", verbose_name="subcategory"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("category", models.ForeignKey(limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.CASCADE, to="products.category")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="creator_%(class)s_objects", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Category",
                "verbose_name_plural": "Sub Categories",
                "ordering": ("category", "name"),
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(blank=True, choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=20, unique=True)),
                (
                    "background_color",
                    models.CharField(choices=[("danger", "red"), ("success", "Green"), ("info", "Blue"), ("warning", "Yellow")], default="success", max_length=10),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="creator_%(class)s_objects", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="productvariant",
            name="tag",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="products.tag"),
        ),
        migrations.CreateModel(
            name="OfferSaleProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(blank=True, choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("deduction", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="creator_%(class)s_objects", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("sale", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.offersale")),
                ("product_varient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.productvariant")),
            ],
            options={
                "unique_together": {("sale", "product_varient")},
            },
        ),
        migrations.CreateModel(
            name="PurchaseProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(blank=True, choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("quantity", models.PositiveIntegerField()),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="creator_%(class)s_objects", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("product_varient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.productvariant")),
                ("purchase", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.purchase")),
            ],
            options={
                "unique_together": {("purchase", "product_varient")},
            },
        ),
    ]
