# Generated by Django 5.0.1 on 2025-03-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cities",
            field=models.ManyToManyField(blank=True, related_name="products", to="products.city"),
        ),
    ]
