# Generated by Django 5.0.1 on 2025-03-29 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_cities"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["order"], "verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
