# Generated by Django 5.0.1 on 2025-03-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_list_home",
            field=models.BooleanField(default=False),
        ),
    ]
