# Generated by Django 5.0.1 on 2025-04-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_category_is_list_home"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Category Active?"),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_cake",
            field=models.BooleanField(default=False, verbose_name="Mark as Cake Category"),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_list_home",
            field=models.BooleanField(default=False, verbose_name="Show on Home Page"),
        ),
    ]
