# Generated by Django 5.0.1 on 2025-07-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_category_is_active_alter_category_is_cake_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="feature_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="featurespec",
            name="specification_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="featurespec",
            name="specification_value",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(blank=True, help_text=" The recommended size is 800x600 pixels.", null=True, upload_to="products/"),
        ),
    ]
